version: '3'
services:
  zap-gui:
    build: 
      context: .
    environment:
      SCREEN_WIDTH: 1440
      SCREEN_HEIGHT: 900
      PYTHONBUFFERED: 1
    ports:
      - 8090:8090
    extra_hosts:
      - "zap:127.0.0.1"
    command: ./recorder.sh
    volumes:
      - ./output:/zap/output